### ISSUE TITLE
Debug：七合一环境传感器测试

### ISSUE THREAD

**Issue by GX-Nan** [GX-Nan/NRMX#13]

**Comment by sunon518** [comment]
![Image](https://user-images.githubusercontent.com/113175646/191228630-34e701c2-6952-407c-9efc-17d0efc4230c.jpg)

看样子像是编码的错误

**Comment by GX-Nan** [comment]
- @sunon518 找出原因

**Comment by sunon518** [comment]
查看总控接收数据不正常
在TCP/IP端口查看，出现乱码的同时接收端口没有数据

**Comment by thePowst** [comment]
@sunon518 @alumer 查看原因。
- 查看有没有内存溢出现象。

**Comment by sunon518** [comment]
内存泄露，用多线程修改源码测试

**Comment by GX-Nan** [comment]
问题已经由另外一个更新解决。代码等待合并到主线。

**Comment by alumer** [comment]
> 问题已解决-->原因：在循环内不断创建变量导致

![Image](https://user-images.githubusercontent.com/71692074/196922783-9d5fb783-411c-4574-8787-3438f9ae16d6.jpg)

**Comment by alumer** [comment]
> 问题解决-->已合并到主线		

3df9fddae96c749f8a07b33c86b1859d8f523da9
