### ISSUE TITLE
小程序

### ISSUE THREAD

**Issue by GX-Nan** [GX-Nan/NRMX#9]

**Comment by GX-Nan** [comment]
初步实现一下功能
1. 总控界面的创建（5个功能界面）。
2. 开发上述5个功能界面的子界面。

**Comment by thePowst** [comment]
如果已经开始做这个任务了，就把这个移到 In Progress项里面。

**Comment by alumer** [comment]
1、灯光控制界面（前端）--已完成

**Comment by GX-Nan** [comment]
待办：
2. 空调控制界面
3. 窗户/窗帘控制界面
4. 新风控制界面

**Comment by alumer** [comment]
空调控制界面(前端)---已完成

**Comment by alumer** [comment]
窗帘&窗户控制界面（前端）--已完成

**Comment by alumer** [comment]
已完成：
    小程序控制界面(前端)
正在进行：
    小程序后端程序--建立服务器中

**Comment by thePowst** [comment]
进度：
-小程序控制界面push到git服务器端。（9月27日）
-小程序后端程序--建立服务器中。 （~10月10日）

**Comment by GX-Nan** [comment]
控制界面代码已推到主线。(faa3843bdfa0d51d6e5ed7daaf26e8c33ef54831)

**Comment by alumer** [comment]
1、小程序--->上传至onenet--->树莓派接收 （已完成）
2、树莓派---->上传至onenet----->小程序接收（已完成--9.29）
3、树莓派 收发来自onenet的信息 并存（已完成--10.9）
4、树莓派 与 小程序 数据处理（正在进行----10.11）

**Comment by alumer** [comment]
出现意外的问题

**Comment by alumer** [comment]
出现意外的问题

**Comment by alumer** [comment]
**貌似解决：**
传输过慢问题：
     1、网速问题
     2、setData使用过多？（这个可能性比较小但不排除）
     3、onenet传输的速度较慢
服务器信息堆积问题：
     存入本地缓存过多导致信息堆积
   解决方法：
      定时清理缓存（使用这个方法之后延长了使用的时间，但测试下来还是回出现服务器信息堆积问题）

**Comment by alumer** [comment]
**总体已完成--还存在部分细节问题：**

> 灯光控制部分：

- 接收函数部分有部分函数需要进行函数打包，可以多次使用该函数(导致代码可读性比较差)
- 微信端与树莓派端显示信息不对称---辅灯
- Spotlight（辅灯）无法更新--->暂时还没找到是什么问题

> 解析部分（树莓派端）：

- 需要讨论一下需不需要创建结构体--->使用的话对如果在本地创建数据库时有帮助

> 小程序总体：

- 闪回问题：在按下按键之后并不会保持操作后的状态，而是会先返回上一次的状态再进行更新到操作后的状态（有可能是传输速度导致的）
- 解决猜想：
- `1、通过这次传入的数据与上一次传入的的进行对比，如果相同则不进行改变--->尝试过-但没有效果
-  2、通过本地数据与这次传入的数据进行对比---->？？貌似怪怪的--->预计效果估计是没有改善

**Comment by alumer** [comment]
**总体已完成--还存在部分细节问题：**

> 灯光控制部分：

- 接收函数部分有部分函数需要进行函数打包，可以多次使用该函数(导致代码可读性比较差)
- 微信端与树莓派端显示信息不对称---辅灯
- Spotlight（辅灯）无法更新--->暂时还没找到是什么问题

> 解析部分（树莓派端）：

- 需要讨论一下需不需要创建结构体--->使用的话对如果在本地创建数据库时有帮助

> 小程序总体：

- 闪回问题：在按下按键之后并不会保持操作后的状态，而是会先返回上一次的状态再进行更新到操作后的状态（有可能是传输速度导致的）
- 解决猜想：
- `1、通过这次传入的数据与上一次传入的的进行对比，如果相同则不进行改变--->尝试过-但没有效果
-  2、通过本地数据与这次传入的数据进行对比---->？？貌似怪怪的--->预计效果估计是没有改善

**Comment by GX-Nan** [comment]
将于10月26日进行测试。

**Comment by alumer** [comment]
> 已测试完毕

- 之前的窗帘不能同时控制已解决
- 没有出现其他严重问题

**Comment by alumer** [comment]
> **补充：缺少室内空气质量得上传**
